### ISSUE TITLE
how to load this code?

### ISSUE THREAD

**Issue by hendrik607** [DavyLandman/p1-esp8266#2]
Hi, i am sorry for asking a question that maybe stupid. I was looking at https://github.com/daniel-jong/esp8266_p1meter an build this board. Loading the .INO gave me some errors and lookin on the issues tab, i came across this solution. Coulbe be the way to go for me, want to test it. I understand that i have to rename the secret file after i edited it. But how do i load youre files onto the ESP? I expected a .INO file. Thanks!

**Comment by DavyLandman** [comment]
It's build and uploaded using [platformio](https://platformio.org/). once you have that up and running you can compile & flash it either from the IDE or command line.

**Comment by hendrik607** [comment]
i looked into that, buit i aint going to be able to use it, not familiar with it. Is it possible to maybe add a arduino file or ESPhome code? Thanks in advance !

**Comment by DavyLandman** [comment]
I do not have the time to help you with that. You could try renaming the `src/main.cpp` to ino and see where you can get. But it won't be compatible with ESPHome.

**Comment by DavyLandman** [comment]
The readme has been updated, I'm closing this issue, if unclear please re-open and point it out.
