### ISSUE TITLE
Which Home-Assistant integration can connect?

### ISSUE THREAD

**Issue by FrankZZ** [DavyLandman/p1-esp8266#3]
Hi Davy,

Thanks for sharing this project. I have flashed it and I can connect via telnet and see the data.
However; which Home-Assistant integration should connect to this host? 

Regards,

Frank

**Comment by FrankZZ** [comment]
I think I can answer my own question. It works with this one:
https://www.home-assistant.io/integrations/dsmr/

**Comment by DavyLandman** [comment]
Exactly, it's emulating the `ser2net` connection type..

If you want, you could help me out with a PR for the readme with an example config? (and how to set it up)

**Comment by FrankZZ** [comment]
Expect that PR soon!

**Comment by FrankZZ** [comment]
@DavyLandman PR created. https://github.com/DavyLandman/p1-esp8266/pull/4
